#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=05

PROG=/opt/bin/nlbw_2_influxdb3v2

cache_file_path="/tmp/nlbw_2_influxdb3.maclist.json"

# **User mac to host name mapping file**
user_list_path="/opt/bin/nlbw_2_influxdb3.maclist.txt"
# **this is the local domain that will be removed from any nslookup hostnames**
# **this could be .local, .localdomain, .home.arpa, etc.
remove_local_domain=".localdomain"
# **InfluxDB Configuration**
# change for your ip address or hostname and port
# change to your databse, keep the second precision
influxdb_url="http://<ip address>:8181/api/v3/write_lp?db=<your database name here>&precision=second"
# replace by your token
influxdb_token="your_influxdb_token_here"

start_service() {
    procd_open_instance
    procd_set_param command $PROG \
        --cache_file_path $cache_file_path \
        --user_list_path $user_list_path \
        --remove_local_domain $remove_local_domain \
        --influxdb_url $influxdb_url \
        --influxdb_token $influxdb_token
    procd_set_param respawn     # Automatically restart service if it crashes
    procd_set_param stdout 1    # Redirect standard output to system log
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # No need to manually stop, Procd handles it
    :
}
