#!/bin/sh /etc/rc.common

USE_PROCD=1
NAME=nlbw_2_influxdb3
START=95
STOP=05

PROG=/opt/bin/nlbw_2_influxdb3.lua

add_option() {
    local cfg="$1"
    local flag="$2"
    local option="$3"
    local default="$4"
    local value

    config_get value "$cfg" "$option" "$default"
    [ -n "$value" ] && procd_append_param command "$flag=$value"
}

parse_config() {
    local cfg="$1"

    add_option "$cfg" cache_file_path cache_file_path "/tmp/nlbw_2_influxdb3.maclist.json"
    add_option "$cfg" user_list_path user_list_path "/opt/bin/nlbw_2_influxdb3.maclist.txt"
    add_option "$cfg" remove_local_domain remove_local_domain ".local"
    add_option "$cfg" influxdb_url influxdb_url "http://localhost:8181/api/v3/write_lp?db=nlbwmon&precision=second"
    add_option "$cfg" influxdb_token influxdb_token "your_influxdb_token_here"
    add_option "$cfg" debug debug false
    add_option "$cfg" interval interval 300
}

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn     # Automatically restart service if it crashes
    procd_set_param stdout 1    # Redirect standard output to system log
    procd_set_param stderr 1
    config_load $NAME
    config_foreach parse_config $NAME
    procd_close_instance
}

stop_service() {
    # No need to manually stop, Procd handles it
    :
}

service_triggers() {
     # self config reload trigger
     procd_add_reload_trigger "/etc/init.d/nlbw_2_influxdb3"
 }
